[workspace]
members = ["dearrow-browser-server", "dearrow-browser-api", "dearrow-parser", "dearrow-browser-frontend"]
resolver = "2"

[workspace.package]
version = "1.2.0"
homepage = "https://dearrow.minibomba.pro"
repository = "https://github.com/mini-bomba/DeArrowBrowser"
license = "AGPL-3.0-only"
edition = "2021"

[workspace.dependencies]
serde = { version = "1.0.194", features = ["derive", "rc"] }
anyhow = "1.0.79"

[profile.release]
strip = true
lto = true
